<?php
/**
 * @file
 * Install, update, and uninstall functions for the Enhanced Number Display module.
 */

/**
 * Upgrade from Drupal 7.
 */
function endo_update_1000() {
  // Convert D7 variables to config.
  $config = config('endo.settings');
  $config->set('opinion_of_backdrop', update_variable_get('endo_opinion_drupal', 'Awesome!'));
  $config->save();

  // Delete D7 variables.
  update_variable_del('endo_opinion_drupal');
}
